/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as ArtworkSlugRouteImport } from './routes/artwork.$slug'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminWhatsappIndexRouteImport } from './routes/admin/whatsapp/index'
import { Route as AdminWebsiteContentIndexRouteImport } from './routes/admin/website-content/index'
import { Route as AdminVisualAssetsIndexRouteImport } from './routes/admin/visual-assets/index'
import { Route as AdminShopCategoriesIndexRouteImport } from './routes/admin/shop-categories/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSeoIndexRouteImport } from './routes/admin/seo/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin/leads/index'
import { Route as AdminFaqsIndexRouteImport } from './routes/admin/faqs/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminArtworksIndexRouteImport } from './routes/admin/artworks/index'
import { Route as ShopProductSlugRouteImport } from './routes/shop.product.$slug'
import { Route as ShopCollectionsSlugRouteImport } from './routes/shop.collections.$slug'
import { Route as AdminWebsiteContentHomepageRouteImport } from './routes/admin/website-content/homepage'
import { Route as AdminWebsiteContentFooterRouteImport } from './routes/admin/website-content/footer'
import { Route as AdminWebsiteContentContactRouteImport } from './routes/admin/website-content/contact'
import { Route as AdminWebsiteContentAboutRouteImport } from './routes/admin/website-content/about'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminMediaIdRouteImport } from './routes/admin/media/$id'
import { Route as AdminArtworksNewRouteImport } from './routes/admin/artworks/new'
import { Route as AdminVisualAssetsEditIdRouteImport } from './routes/admin/visual-assets/edit.$id'
import { Route as AdminShopCategoriesEditIdRouteImport } from './routes/admin/shop-categories/edit.$id'
import { Route as AdminProductsEditIdRouteImport } from './routes/admin/products/edit.$id'
import { Route as AdminCategoriesEditIdRouteImport } from './routes/admin/categories/edit.$id'
import { Route as AdminArtworksEditIdRouteImport } from './routes/admin/artworks/edit.$id'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArtworkSlugRoute = ArtworkSlugRouteImport.update({
  id: '/artwork/$slug',
  path: '/artwork/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWhatsappIndexRoute = AdminWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWebsiteContentIndexRoute =
  AdminWebsiteContentIndexRouteImport.update({
    id: '/website-content/',
    path: '/website-content/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminVisualAssetsIndexRoute = AdminVisualAssetsIndexRouteImport.update({
  id: '/visual-assets/',
  path: '/visual-assets/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopCategoriesIndexRoute =
  AdminShopCategoriesIndexRouteImport.update({
    id: '/shop-categories/',
    path: '/shop-categories/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeoIndexRoute = AdminSeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqsIndexRoute = AdminFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtworksIndexRoute = AdminArtworksIndexRouteImport.update({
  id: '/artworks/',
  path: '/artworks/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/shop/product/$slug',
  path: '/shop/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCollectionsSlugRoute = ShopCollectionsSlugRouteImport.update({
  id: '/shop/collections/$slug',
  path: '/shop/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteContentHomepageRoute =
  AdminWebsiteContentHomepageRouteImport.update({
    id: '/website-content/homepage',
    path: '/website-content/homepage',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWebsiteContentFooterRoute =
  AdminWebsiteContentFooterRouteImport.update({
    id: '/website-content/footer',
    path: '/website-content/footer',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWebsiteContentContactRoute =
  AdminWebsiteContentContactRouteImport.update({
    id: '/website-content/contact',
    path: '/website-content/contact',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminWebsiteContentAboutRoute =
  AdminWebsiteContentAboutRouteImport.update({
    id: '/website-content/about',
    path: '/website-content/about',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIdRoute = AdminMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtworksNewRoute = AdminArtworksNewRouteImport.update({
  id: '/artworks/new',
  path: '/artworks/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVisualAssetsEditIdRoute = AdminVisualAssetsEditIdRouteImport.update({
  id: '/visual-assets/edit/$id',
  path: '/visual-assets/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopCategoriesEditIdRoute =
  AdminShopCategoriesEditIdRouteImport.update({
    id: '/shop-categories/edit/$id',
    path: '/shop-categories/edit/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsEditIdRoute = AdminProductsEditIdRouteImport.update({
  id: '/products/edit/$id',
  path: '/products/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesEditIdRoute = AdminCategoriesEditIdRouteImport.update({
  id: '/categories/edit/$id',
  path: '/categories/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArtworksEditIdRoute = AdminArtworksEditIdRouteImport.update({
  id: '/artworks/edit/$id',
  path: '/artworks/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/artwork/$slug': typeof ArtworkSlugRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/admin/media/$id': typeof AdminMediaIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/website-content/about': typeof AdminWebsiteContentAboutRoute
  '/admin/website-content/contact': typeof AdminWebsiteContentContactRoute
  '/admin/website-content/footer': typeof AdminWebsiteContentFooterRoute
  '/admin/website-content/homepage': typeof AdminWebsiteContentHomepageRoute
  '/shop/collections/$slug': typeof ShopCollectionsSlugRoute
  '/shop/product/$slug': typeof ShopProductSlugRoute
  '/admin/artworks/': typeof AdminArtworksIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/seo/': typeof AdminSeoIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shop-categories/': typeof AdminShopCategoriesIndexRoute
  '/admin/visual-assets/': typeof AdminVisualAssetsIndexRoute
  '/admin/website-content/': typeof AdminWebsiteContentIndexRoute
  '/admin/whatsapp/': typeof AdminWhatsappIndexRoute
  '/admin/artworks/edit/$id': typeof AdminArtworksEditIdRoute
  '/admin/categories/edit/$id': typeof AdminCategoriesEditIdRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
  '/admin/shop-categories/edit/$id': typeof AdminShopCategoriesEditIdRoute
  '/admin/visual-assets/edit/$id': typeof AdminVisualAssetsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/artwork/$slug': typeof ArtworkSlugRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/admin/media/$id': typeof AdminMediaIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/website-content/about': typeof AdminWebsiteContentAboutRoute
  '/admin/website-content/contact': typeof AdminWebsiteContentContactRoute
  '/admin/website-content/footer': typeof AdminWebsiteContentFooterRoute
  '/admin/website-content/homepage': typeof AdminWebsiteContentHomepageRoute
  '/shop/collections/$slug': typeof ShopCollectionsSlugRoute
  '/shop/product/$slug': typeof ShopProductSlugRoute
  '/admin/artworks': typeof AdminArtworksIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/faqs': typeof AdminFaqsIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/seo': typeof AdminSeoIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/shop-categories': typeof AdminShopCategoriesIndexRoute
  '/admin/visual-assets': typeof AdminVisualAssetsIndexRoute
  '/admin/website-content': typeof AdminWebsiteContentIndexRoute
  '/admin/whatsapp': typeof AdminWhatsappIndexRoute
  '/admin/artworks/edit/$id': typeof AdminArtworksEditIdRoute
  '/admin/categories/edit/$id': typeof AdminCategoriesEditIdRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
  '/admin/shop-categories/edit/$id': typeof AdminShopCategoriesEditIdRoute
  '/admin/visual-assets/edit/$id': typeof AdminVisualAssetsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/artwork/$slug': typeof ArtworkSlugRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/admin/media/$id': typeof AdminMediaIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/website-content/about': typeof AdminWebsiteContentAboutRoute
  '/admin/website-content/contact': typeof AdminWebsiteContentContactRoute
  '/admin/website-content/footer': typeof AdminWebsiteContentFooterRoute
  '/admin/website-content/homepage': typeof AdminWebsiteContentHomepageRoute
  '/shop/collections/$slug': typeof ShopCollectionsSlugRoute
  '/shop/product/$slug': typeof ShopProductSlugRoute
  '/admin/artworks/': typeof AdminArtworksIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/seo/': typeof AdminSeoIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shop-categories/': typeof AdminShopCategoriesIndexRoute
  '/admin/visual-assets/': typeof AdminVisualAssetsIndexRoute
  '/admin/website-content/': typeof AdminWebsiteContentIndexRoute
  '/admin/whatsapp/': typeof AdminWhatsappIndexRoute
  '/admin/artworks/edit/$id': typeof AdminArtworksEditIdRoute
  '/admin/categories/edit/$id': typeof AdminCategoriesEditIdRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
  '/admin/shop-categories/edit/$id': typeof AdminShopCategoriesEditIdRoute
  '/admin/visual-assets/edit/$id': typeof AdminVisualAssetsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/track-order'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/subscribers'
    | '/artwork/$slug'
    | '/order-confirmation/$orderId'
    | '/shop/$category'
    | '/admin/'
    | '/shop/'
    | '/admin/artworks/new'
    | '/admin/media/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/website-content/about'
    | '/admin/website-content/contact'
    | '/admin/website-content/footer'
    | '/admin/website-content/homepage'
    | '/shop/collections/$slug'
    | '/shop/product/$slug'
    | '/admin/artworks/'
    | '/admin/categories/'
    | '/admin/faqs/'
    | '/admin/leads/'
    | '/admin/media/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/seo/'
    | '/admin/settings/'
    | '/admin/shop-categories/'
    | '/admin/visual-assets/'
    | '/admin/website-content/'
    | '/admin/whatsapp/'
    | '/admin/artworks/edit/$id'
    | '/admin/categories/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/shop-categories/edit/$id'
    | '/admin/visual-assets/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/track-order'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/subscribers'
    | '/artwork/$slug'
    | '/order-confirmation/$orderId'
    | '/shop/$category'
    | '/admin'
    | '/shop'
    | '/admin/artworks/new'
    | '/admin/media/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/website-content/about'
    | '/admin/website-content/contact'
    | '/admin/website-content/footer'
    | '/admin/website-content/homepage'
    | '/shop/collections/$slug'
    | '/shop/product/$slug'
    | '/admin/artworks'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/shop-categories'
    | '/admin/visual-assets'
    | '/admin/website-content'
    | '/admin/whatsapp'
    | '/admin/artworks/edit/$id'
    | '/admin/categories/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/shop-categories/edit/$id'
    | '/admin/visual-assets/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/services'
    | '/track-order'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/subscribers'
    | '/artwork/$slug'
    | '/order-confirmation/$orderId'
    | '/shop/$category'
    | '/admin/'
    | '/shop/'
    | '/admin/artworks/new'
    | '/admin/media/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/admin/website-content/about'
    | '/admin/website-content/contact'
    | '/admin/website-content/footer'
    | '/admin/website-content/homepage'
    | '/shop/collections/$slug'
    | '/shop/product/$slug'
    | '/admin/artworks/'
    | '/admin/categories/'
    | '/admin/faqs/'
    | '/admin/leads/'
    | '/admin/media/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/seo/'
    | '/admin/settings/'
    | '/admin/shop-categories/'
    | '/admin/visual-assets/'
    | '/admin/website-content/'
    | '/admin/whatsapp/'
    | '/admin/artworks/edit/$id'
    | '/admin/categories/edit/$id'
    | '/admin/products/edit/$id'
    | '/admin/shop-categories/edit/$id'
    | '/admin/visual-assets/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  TrackOrderRoute: typeof TrackOrderRoute
  ArtworkSlugRoute: typeof ArtworkSlugRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsSlugRoute: typeof ShopCollectionsSlugRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork/$slug': {
      id: '/artwork/$slug'
      path: '/artwork/$slug'
      fullPath: '/artwork/$slug'
      preLoaderRoute: typeof ArtworkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/whatsapp/': {
      id: '/admin/whatsapp/'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp/'
      preLoaderRoute: typeof AdminWhatsappIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/website-content/': {
      id: '/admin/website-content/'
      path: '/website-content'
      fullPath: '/admin/website-content/'
      preLoaderRoute: typeof AdminWebsiteContentIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/visual-assets/': {
      id: '/admin/visual-assets/'
      path: '/visual-assets'
      fullPath: '/admin/visual-assets/'
      preLoaderRoute: typeof AdminVisualAssetsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop-categories/': {
      id: '/admin/shop-categories/'
      path: '/shop-categories'
      fullPath: '/admin/shop-categories/'
      preLoaderRoute: typeof AdminShopCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seo/': {
      id: '/admin/seo/'
      path: '/seo'
      fullPath: '/admin/seo/'
      preLoaderRoute: typeof AdminSeoIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faqs/': {
      id: '/admin/faqs/'
      path: '/faqs'
      fullPath: '/admin/faqs/'
      preLoaderRoute: typeof AdminFaqsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artworks/': {
      id: '/admin/artworks/'
      path: '/artworks'
      fullPath: '/admin/artworks/'
      preLoaderRoute: typeof AdminArtworksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shop/product/$slug': {
      id: '/shop/product/$slug'
      path: '/shop/product/$slug'
      fullPath: '/shop/product/$slug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/collections/$slug': {
      id: '/shop/collections/$slug'
      path: '/shop/collections/$slug'
      fullPath: '/shop/collections/$slug'
      preLoaderRoute: typeof ShopCollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website-content/homepage': {
      id: '/admin/website-content/homepage'
      path: '/website-content/homepage'
      fullPath: '/admin/website-content/homepage'
      preLoaderRoute: typeof AdminWebsiteContentHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/website-content/footer': {
      id: '/admin/website-content/footer'
      path: '/website-content/footer'
      fullPath: '/admin/website-content/footer'
      preLoaderRoute: typeof AdminWebsiteContentFooterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/website-content/contact': {
      id: '/admin/website-content/contact'
      path: '/website-content/contact'
      fullPath: '/admin/website-content/contact'
      preLoaderRoute: typeof AdminWebsiteContentContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/website-content/about': {
      id: '/admin/website-content/about'
      path: '/website-content/about'
      fullPath: '/admin/website-content/about'
      preLoaderRoute: typeof AdminWebsiteContentAboutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/$id': {
      id: '/admin/media/$id'
      path: '/media/$id'
      fullPath: '/admin/media/$id'
      preLoaderRoute: typeof AdminMediaIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artworks/new': {
      id: '/admin/artworks/new'
      path: '/artworks/new'
      fullPath: '/admin/artworks/new'
      preLoaderRoute: typeof AdminArtworksNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/visual-assets/edit/$id': {
      id: '/admin/visual-assets/edit/$id'
      path: '/visual-assets/edit/$id'
      fullPath: '/admin/visual-assets/edit/$id'
      preLoaderRoute: typeof AdminVisualAssetsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shop-categories/edit/$id': {
      id: '/admin/shop-categories/edit/$id'
      path: '/shop-categories/edit/$id'
      fullPath: '/admin/shop-categories/edit/$id'
      preLoaderRoute: typeof AdminShopCategoriesEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/edit/$id': {
      id: '/admin/products/edit/$id'
      path: '/products/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AdminProductsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/edit/$id': {
      id: '/admin/categories/edit/$id'
      path: '/categories/edit/$id'
      fullPath: '/admin/categories/edit/$id'
      preLoaderRoute: typeof AdminCategoriesEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/artworks/edit/$id': {
      id: '/admin/artworks/edit/$id'
      path: '/artworks/edit/$id'
      fullPath: '/admin/artworks/edit/$id'
      preLoaderRoute: typeof AdminArtworksEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArtworksNewRoute: typeof AdminArtworksNewRoute
  AdminMediaIdRoute: typeof AdminMediaIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminWebsiteContentAboutRoute: typeof AdminWebsiteContentAboutRoute
  AdminWebsiteContentContactRoute: typeof AdminWebsiteContentContactRoute
  AdminWebsiteContentFooterRoute: typeof AdminWebsiteContentFooterRoute
  AdminWebsiteContentHomepageRoute: typeof AdminWebsiteContentHomepageRoute
  AdminArtworksIndexRoute: typeof AdminArtworksIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminFaqsIndexRoute: typeof AdminFaqsIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminSeoIndexRoute: typeof AdminSeoIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminShopCategoriesIndexRoute: typeof AdminShopCategoriesIndexRoute
  AdminVisualAssetsIndexRoute: typeof AdminVisualAssetsIndexRoute
  AdminWebsiteContentIndexRoute: typeof AdminWebsiteContentIndexRoute
  AdminWhatsappIndexRoute: typeof AdminWhatsappIndexRoute
  AdminArtworksEditIdRoute: typeof AdminArtworksEditIdRoute
  AdminCategoriesEditIdRoute: typeof AdminCategoriesEditIdRoute
  AdminProductsEditIdRoute: typeof AdminProductsEditIdRoute
  AdminShopCategoriesEditIdRoute: typeof AdminShopCategoriesEditIdRoute
  AdminVisualAssetsEditIdRoute: typeof AdminVisualAssetsEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArtworksNewRoute: AdminArtworksNewRoute,
  AdminMediaIdRoute: AdminMediaIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminWebsiteContentAboutRoute: AdminWebsiteContentAboutRoute,
  AdminWebsiteContentContactRoute: AdminWebsiteContentContactRoute,
  AdminWebsiteContentFooterRoute: AdminWebsiteContentFooterRoute,
  AdminWebsiteContentHomepageRoute: AdminWebsiteContentHomepageRoute,
  AdminArtworksIndexRoute: AdminArtworksIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminFaqsIndexRoute: AdminFaqsIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminSeoIndexRoute: AdminSeoIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminShopCategoriesIndexRoute: AdminShopCategoriesIndexRoute,
  AdminVisualAssetsIndexRoute: AdminVisualAssetsIndexRoute,
  AdminWebsiteContentIndexRoute: AdminWebsiteContentIndexRoute,
  AdminWhatsappIndexRoute: AdminWhatsappIndexRoute,
  AdminArtworksEditIdRoute: AdminArtworksEditIdRoute,
  AdminCategoriesEditIdRoute: AdminCategoriesEditIdRoute,
  AdminProductsEditIdRoute: AdminProductsEditIdRoute,
  AdminShopCategoriesEditIdRoute: AdminShopCategoriesEditIdRoute,
  AdminVisualAssetsEditIdRoute: AdminVisualAssetsEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  TrackOrderRoute: TrackOrderRoute,
  ArtworkSlugRoute: ArtworkSlugRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsSlugRoute: ShopCollectionsSlugRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
